name: Java CI
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      working-directory-fileupload: "./Path Manipulation/while File Upload/java/fileupload.pathmanipulation"
      working-directory-fileread: "./Path Manipulation/while File Read/java/fileread.pathmanipulation"
      working-directory-unrestricted-fileupload: "./Unrestriced File Upload/java"

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Build with Maven for Path Manipulation while File Upload
        working-directory: ${{ env.working-directory-fileupload }}
        run: mvn clean -B package --file pom.xml

      - name: Build with Maven for Path Manipulation while File Read
        working-directory: ${{ env.working-directory-fileread }}
        run: mvn clean -B package --file pom.xml

      - name: Build with Maven for Unrestricted File Upload
        working-directory: ${{ working-directory-unrestricted-fileupload }}
        run: mvn clean -B package --file pom.xml

      - name: Run tests for Path Manipulation while File Upload
        working-directory: ${{ env.working-directory-fileupload }}
        run: mvn test

      - name: Run tests for Unrestricted File Upload
        working-directory: ${{ working-directory-unrestricted-fileupload }}
        run: mvn test

      - name: Run tests for Path Manipulation while File Read
        working-directory: ${{ env.working-directory-fileread }}
        run: mvn test

      - name: Clean up for Path Manipulation while File Upload
        working-directory: ${{ env.working-directory-fileupload }}
        run: mvn clean

      - name: Clean up for Path Manipulation while File Read
        working-directory: ${{ env.working-directory-fileread }}
        run: mvn clean

      - name: Clean up for Unrestricted File Upload
        working-directory: ${{ working-directory-unrestricted-fileupload }}
        run: mvn clean